update open path alias

diff --git a/.helpers/open/get_repo_url b/.helpers/open/get_repo_url
--- a/.helpers/open/get_repo_url
+++ b/.helpers/open/get_repo_url
@@ -5,4 +5,9 @@ if [ "${url:(-4)}" == ".git" ]; then
     url="$( echo "${url%.*}" )"
 fi
 
+if [ -z "${url}" ]; then
+    echo -e "${B_RED}${T_WHITE}ERROR:${F_RESET} no repository or url found"
+    exit 1
+fi
+
 echo "$url"
